<?php
class bb {
	private static $smilies_code = array(
		':)',
		';)',
		':wink:',
		':D',
		':P',
		':(',
		":'(",
		':|',
		':-)',
		':-(',
		':-P',
		';-)',
		':-|',
		':-/',
		":'-(",
		':-O',
		':o)',
		'8-)',
		'|-)',
		':-D',
		'O:-',
		':angelic:',
		':halo:',
		':kiss:',
		':winkkiss:',
		':sleeping:',
		'-_-',
		':clown:',
		':mml:',
		':cloud9:',
		':smile:',
		':lol:',
		':wink2:',
		':w00t:',
		':w000t:',
		':wow:',
		':weep:',
		':crybaby:',
		':innocent:',
		':whistle:',
		':unsure:',
		':doubt:',
		':closedeyes:',
		':cool:',
		':fun:',
		':hihi:',
		':thumbup:',
		':thumbsup:',
		':thumbsdown:',
		':blush:',
		':smirksweat:',
		':unsure:',
		':yes:',
		':no:',
		':nono:',
		':love:',
		':heartbeat:',
		':?:',
		':!:',
		':idea:',
		':idea2:',
		':arrow:',
		':arrow2:',
		':hmm:',
		':hmmm:',
		':huh:',
		':eyebrow:',
		':shrug:',
		':geek:',
		':look:',
		':rolleyes:',
		':shifty:',
		':blink:',
		':smartass:',
		':sick:',
		':sick2:',
		':shocking:',
		':crazy:',
		':crazy2:',
		':wacko:',
		':princo:',
		':silly:',
		':dense:',
		':alien:',
		':wizard:',
		':wave:',
		':wavecry:',
		':baby:',
		':grrr:',
		':angry:',
		':fist:',
		':ras:',
		':annoyed:',
		':sly:',
		':evil:',
		':devil:',
		':devil2:',
		':evilmad:',
		':sneaky:',
		':axe:',
		':slap:',
		':wall:',
		':argue:',
		':catfight:',
		':stretcher:',
		':rant:',
		':rant2:',
		':wag:',
		':upyours:',
		':fighting:',
		':rtfm:',
		':rules:',
		':banned:',
		':jump:',
		':yucky:',
		':nugget:',
		':blowup:',
		':smart:',
		':popsi:',
		':shutup:',
		':shutup2:',
		':censored:',
		':censored2:',
		':spam2:',
		':crockett:',
		':zorro:',
		':snap:',
		':beer:',
		':beer2:',
		':drunk:',
		':strongbench:',
		':weakbench:',
		':dumbells:',
		':gone:',
		':music:',
		':rb:',
		':rblocked:',
		':locked:',
		':maxlocked:',
		':hslocked:',
		':stupid:',
		':dots:',
		':offtopic:',
		':spam:',
		':oops:',
		':lttd:',
		':please:',
		':sorry:',
		':hi:',
		':rtf:',
		':morepics:',
		':beta:',
		':busted:',
		':huhsign:',
		':yesmaster:',
		':protest:',
		':rockon:',
		':google:',
		':google2:',
		':ewiki:',
		':bump:',
		':bump2:',
		':irule:',
		':yay:',
		':cake:',
		':cake2:',
		':hbd:',
		':band:',
		':punk:',
		':rofl:',
		':bounce:',
		':mbounce:',
		':thankyou:',
		':thankyou2:',
		':gathering:',
		':hang:',
		':chop:',
		':rip:',
		':hurt:',
		':whip:',
		':whip2:',
		':judge:',
		':chair:',
		':tease:',
		':box:',
		':boxing:',
		':guns:',
		':guns2:',
		':rungun:',
		':sniper:',
		':shoot:',
		':shoot2:',
		':flowers:',
		':flowers2:',
		':wub:',
		':lovers:',
		':kissing:',
		':kissing2:',
		':handshake:',
		':console:',
		':group:',
		':pile:',
		':hump:',
		':wanking:',
		':hooray:',
		':happy2:',
		':clap:',
		':clap2:',
		':danceboy:',
		':dancing:',
		':weirdo:',
		':yawn:',
		':bow:',
		':dawgie:',
		':cylon:',
		':coffee:',
		':book:',
		':fish:',
		':mama:',
		':pepsi:',
		':cookies:',
		':pizza:',
		':medieval:',
		':rambo:',
		':ninja:',
		':ninjafist:',
		':ninjajig:',
		':ninjawave:',
		':ninjahide:',
		':ninja2:',
		':diablo:',
		':hannibal:',
		':party:',
		':snorkle:',
		':evo:',
		':king:',
		':chef:',
		':mario:',
		':pope:',
		':fez:',
		':cap:',
		':cowboy:',
		':pirate:',
		':pirate2:',
		':rock:',
		':smokin:',
		':cigar:',
		':icecream:',
		':phead:',
		':juggle:',
		':oldtimer:',
		':trampoline:',
		':banana:',
		':banana2:',
		':bananahump:',
		':carrot:',
		':dog:',
		':smurf:',
		':yikes:',
		':osama:',
		':saddam:',
		':santa:',
		':brownie:',
		':indian:',
		':sphinx:',
		':pimp:',
		':mrt:',
		':nuke:',
		':jacko:',
		':ike:',
		':greedy:',
		':super:',
		':wolverine:',
		':starwars:',
		':jedi:',
		':jedi2:',
		':matrix:',
		':spidey:',
		':spider:',
		':bandana:',
		':construction:',
		':sheep:',
		':badger:',
		':police:',
		':detective:',
		':mug:',
		':bike:',
		':bike2:',
		':alonso:',
		':kimi:',
		':schumi:',
		':fishing:',
		':flutterby:',
		':reindeer:',
		':clover:',
		':horse:',
		':shit:',
		':soldiers:',
		':throw:',
		':blowie:',
		':firefox:',
		':boozer:',
		':deadhorse:',
		':spank:',
		':yoji:',
		':whacky:',
		':gumicsirke:'
	);

	private static $smilies_img = array(
		'[smyle=smile1.gif]',
		'[smyle=wink.gif]',
		'[smyle=wink.gif]',
		'[smyle=grin.gif]',
		'[smyle=tongue.gif]',
		'[smyle=sad.gif]',
		'[smyle=cry.gif]',
		'[smyle=noexpression.gif]',
		'[smyle=smile1.gif]',
		'[smyle=sad.gif]',
		'[smyle=tongue.gif]',
		'[smyle=wink.gif]',
		'[smyle=noexpression.gif]',
		'[smyle=confused.gif]',
		'[smyle=cry.gif]',
		'[smyle=ohmy.gif]',
		'[smyle=clown.gif]',
		'[smyle=cool1.gif]',
		'[smyle=sleeping.gif]',
		'[smyle=grin.gif]',
		'[smyle=innocent.gif]',
		'[smyle=angelic.gif]',
		'[smyle=halo.gif]',
		'[smyle=kiss.gif]',
		'[smyle=winkkiss.gif]',
		'[smyle=sleeping.gif]',
		'[smyle=unsure.gif]',
		'[smyle=clown.gif]',
		'[smyle=mml.gif]',
		'[smyle=cloud9.gif]',
		'[smyle=smile2.gif]',
		'[smyle=laugh.gif]',
		'[smyle=wink2.gif]',
		'[smyle=w00t.gif]',
		'[smyle=w000t.gif]',
		'[smyle=wow.gif]',
		'[smyle=weep.gif]',
		'[smyle=crybaby.gif]',
		'[smyle=innocent.gif]',
		'[smyle=whistle.gif]',
		'[smyle=unsure.gif]',
		'[smyle=doubt.gif]',
		'[smyle=closedeyes.gif]',
		'[smyle=cool2.gif]',
		'[smyle=fun.gif]',
		'[smyle=hihi.gif]',
		'[smyle=thumbup.gif]',
		'[smyle=thumbsup.gif]',
		'[smyle=thumbsdown.gif]',
		'[smyle=blush.gif]',
		'[smyle=smirksweat.gif]',
		'[smyle=unsure.gif]',
		'[smyle=yes.gif]',
		'[smyle=no.gif]',
		'[smyle=nono.gif]',
		'[smyle=love.gif]',
		'[smyle=heartbeat.gif]',
		'[smyle=question.gif]',
		'[smyle=excl.gif]',
		'[smyle=idea.gif]',
		'[smyle=idea2.gif]',
		'[smyle=arrow.gif]',
		'[smyle=arrow2.gif]',
		'[smyle=hmm.gif]',
		'[smyle=hmmm.gif]',
		'[smyle=huh.gif]',
		'[smyle=eyebrow.gif]',
		'[smyle=shrug.gif]',
		'[smyle=geek.gif]',
		'[smyle=look.gif]',
		'[smyle=rolleyes.gif]',
		'[smyle=shifty.gif]',
		'[smyle=blink.gif]',
		'[smyle=smartass.gif]',
		'[smyle=sick.gif]',
		'[smyle=sick2.gif]',
		'[smyle=shocking.gif]',
		'[smyle=crazy.gif]',
		'[smyle=crazy2.gif]',
		'[smyle=wacko.gif]',
		'[smyle=princo.gif]',
		'[smyle=silly-hedge.gif]',
		'[smyle=dense.gif]',
		'[smyle=alien.gif]',
		'[smyle=wizard.gif]',
		'[smyle=wave.gif]',
		'[smyle=wavecry.gif]',
		'[smyle=baby.gif]',
		'[smyle=angry.gif]',
		'[smyle=angry.gif]',
		'[smyle=fist.gif]',
		'[smyle=ras.gif]',
		'[smyle=annoyed.gif]',
		'[smyle=sly.gif]',
		'[smyle=evil.gif]',
		'[smyle=devil.gif]',
		'[smyle=devil2.gif]',
		'[smyle=evilmad.gif]',
		'[smyle=sneaky.gif]',
		'[smyle=axe.gif]',
		'[smyle=slap.gif]',
		'[smyle=wall.gif]',
		'[smyle=argue.gif]',
		'[smyle=catfight.gif]',
		'[smyle=stretcher.gif]',
		'[smyle=rant.gif]',
		'[smyle=rant2.gif]',
		'[smyle=wag.gif]',
		'[smyle=upyours.gif]',
		'[smyle=fighting.gif]',
		'[smyle=rtfm.gif]',
		'[smyle=rules.gif]',
		'[smyle=banned.gif]',
		'[smyle=jump.gif]',
		'[smyle=yucky.gif]',
		'[smyle=nugget.gif]',
		'[smyle=blowup.gif]',
		'[smyle=smart.gif]',
		'[smyle=spank.gif]',
		'[smyle=shutup.gif]',
		'[smyle=shutup2.gif]',
		'[smyle=censored.gif]',
		'[smyle=censored2.gif]',
		'[smyle=spam2.gif]',
		'[smyle=crockett.gif]',
		'[smyle=zorro.gif]',
		'[smyle=snap.gif]',
		'[smyle=beer.gif]',
		'[smyle=beer2.gif]',
		'[smyle=drunk.gif]',
		'[smyle=strongbench.gif]',
		'[smyle=weakbench.gif]',
		'[smyle=dumbells.gif]',
		'[smyle=gone.gif]',
		'[smyle=music.gif]',
		'[smyle=rb.gif]',
		'[smyle=rblocked.gif]',
		'[smyle=locked.gif]',
		'[smyle=maxlocked.gif]',
		'[smyle=hslocked.gif]',
		'[smyle=stupid.gif]',
		'[smyle=dots.gif]',
		'[smyle=offtopic.gif]',
		'[smyle=spam.gif]',
		'[smyle=oops.gif]',
		'[smyle=lttd.gif]',
		'[smyle=please.gif]',
		'[smyle=sorry.gif]',
		'[smyle=hi.gif]',
		'[smyle=rtf.gif]',
		'[smyle=morepics.gif]',
		'[smyle=beta.gif]',
		'[smyle=busted.gif]',
		'[smyle=huhsign.gif]',
		'[smyle=yesmaster.gif]',
		'[smyle=protest.gif]',
		'[smyle=rockon.gif]',
		'[smyle=google1.gif]',
		'[smyle=google2.gif]',
		'[smyle=ewiki.gif]',
		'[smyle=bump.gif]',
		'[smyle=bump2.gif]',
		'[smyle=irule.gif]',
		'[smyle=yay.gif]',
		'[smyle=cake.gif]',
		'[smyle=cake2.gif]',
		'[smyle=hbd.gif]',
		'[smyle=band.gif]',
		'[smyle=punk.gif]',
		'[smyle=rofl.gif]',
		'[smyle=bounce.gif]',
		'[smyle=mbounce.gif]',
		'[smyle=thankyou.gif]',
		'[smyle=kosz.gif]',
		'[smyle=gathering.gif]',
		'[smyle=hang.gif]',
		'[smyle=chop.gif]',
		'[smyle=rip.gif]',
		'[smyle=hurt.gif]',
		'[smyle=whip.gif]',
		'[smyle=whip2.gif]',
		'[smyle=judge.gif]',
		'[smyle=chair.gif]',
		'[smyle=tease.gif]',
		'[smyle=box.gif]',
		'[smyle=boxing.gif]',
		'[smyle=guns.gif]',
		'[smyle=guns2.gif]',
		'[smyle=rungun.gif]',
		'[smyle=sniper.gif]',
		'[smyle=shoot.gif]',
		'[smyle=shoot2.gif]',
		'[smyle=flowers.gif]',
		'[smyle=flowers2.gif]',
		'[smyle=wub.gif]',
		'[smyle=lovers.gif]',
		'[smyle=kissing.gif]',
		'[smyle=kissing2.gif]',
		'[smyle=handshake.gif]',
		'[smyle=console.gif]',
		'[smyle=group.gif]',
		'[smyle=pile.gif]',
		'[smyle=hump.gif]',
		'[smyle=wanking.gif]',
		'[smyle=hooray.gif]',
		'[smyle=happy2.gif]',
		'[smyle=clap.gif]',
		'[smyle=clap2.gif]',
		'[smyle=danceboy.gif]',
		'[smyle=dancing.gif]',
		'[smyle=weirdo.gif]',
		'[smyle=yawn.gif]',
		'[smyle=bow.gif]',
		'[smyle=dawgie.gif]',
		'[smyle=cylon.gif]',
		'[smyle=coffee.gif]',
		'[smyle=book.gif]',
		'[smyle=fish.gif]',
		'[smyle=mama.gif]',
		'[smyle=pepsi.gif]',
		'[smyle=cookies.gif]',
		'[smyle=pizza.gif]',
		'[smyle=medieval.gif]',
		'[smyle=rambo.gif]',
		'[smyle=ninja.gif]',
		'[smyle=ninjafist.gif]',
		'[smyle=ninjajig.gif]',
		'[smyle=ninjawave.gif]',
		'[smyle=ninja_hide.gif]',
		'[smyle=ninja2.gif]',
		'[smyle=diablo.gif]',
		'[smyle=hannibal.gif]',
		'[smyle=party.gif]',
		'[smyle=snorkle.gif]',
		'[smyle=evo.gif]',
		'[smyle=king.gif]',
		'[smyle=chef.gif]',
		'[smyle=mario.gif]',
		'[smyle=pope.gif]',
		'[smyle=fez.gif]',
		'[smyle=cap.gif]',
		'[smyle=cowboy.gif]',
		'[smyle=pirate.gif]',
		'[smyle=pirate2.gif]',
		'[smyle=rock.gif]',
		'[smyle=smokin.gif]',
		'[smyle=cigar.gif]',
		'[smyle=icecream.gif]',
		'[smyle=propellerhead.gif]',
		'[smyle=juggle.gif]',
		'[smyle=oldtimer.gif]',
		'[smyle=trampoline.gif]',
		'[smyle=bananadance.gif]',
		'[smyle=bananadance2.gif]',
		'[smyle=bananahump.gif]',
		'[smyle=carrot.gif]',
		'[smyle=dog.gif]',
		'[smyle=smurf.gif]',
		'[smyle=yikes.gif]',
		'[smyle=osama.gif]',
		'[smyle=saddam.gif]',
		'[smyle=santa.gif]',
		'[smyle=brownie.gif]',
		'[smyle=indian.gif]',
		'[smyle=sphinx.gif]',
		'[smyle=pimp.gif]',
		'[smyle=mrt.gif]',
		'[smyle=nuke.gif]',
		'[smyle=jacko.gif]',
		'[smyle=ike.gif]',
		'[smyle=greedy.gif]',
		'[smyle=super.gif]',
		'[smyle=wolverine.gif]',
		'[smyle=starwars.gif]',
		'[smyle=jedi.gif]',
		'[smyle=jedi2.gif]',
		'[smyle=matrix.gif]',
		'[smyle=spidey.gif]',
		'[smyle=spider.gif]',
		'[smyle=bandana.gif]',
		'[smyle=construction.gif]',
		'[smyle=sheep.gif]',
		'[smyle=badger.gif]',
		'[smyle=police.gif]',
		'[smyle=detective.gif]',
		'[smyle=mug.gif]',
		'[smyle=bike.gif]',
		'[smyle=bike2.gif]',
		'[smyle=alonso.gif]',
		'[smyle=kimi.gif]',
		'[smyle=schumacher.gif]',
		'[smyle=fishing.gif]',
		'[smyle=flutterby.gif]',
		'[smyle=reindeer.gif]',
		'[smyle=clover.gif]',
		'[smyle=horse.gif]',
		'[smyle=shit.gif]',
		'[smyle=soldiers.gif]',
		'[smyle=throw.gif]',
		'[smyle=blowie.gif]',
		'[smyle=firefox.gif]',
		'[smyle=alcoholic.gif]',
		'[smyle=deadhorse.gif]',
		'[smyle=spank.gif]',
		'[smyle=yoji.gif]',
		'[smyle=whacky.gif]',
		'[smyle=gumicsirke.gif]'
	);

	private function __construct() {}

	private function whatbrowser() {
		$browser = array (
			"OPERA",
			"MSIE",
			"NETSCAPE",
			"FIREFOX",
			"SAFARI",
			"KONQUEROR",
			"MOZILLA"
		);
					
		$info['browser'] = "OTHER";
		foreach ($browser as $parent) {
			if(($s = strpos(strtoupper($_SERVER['HTTP_USER_AGENT']), $parent)) !== FALSE) {
				$f = $s + strlen($parent);
				$version = substr($_SERVER['HTTP_USER_AGENT'], $f, 5);
				$version = preg_replace('/[^0-9,.]/', '', $version);
				$info['browser'] = $parent;
				$info['version'] = $version;
				break;
			}
		}
		return $info;
	}

	public function bbdecode($message, $mode = NULL) {
		if($mode == 1) {
			$pic1 = "<div class=\"layer\"><img border=\"0\" class=\"description\" src=\"kinezet/".$GLOBALS['USER']['smink']."/torrent_view.jpg\" alt=\"\"/><a href=\"\\1\" title=\"Csatolt kép megnyitása\" target=\"_blank\">&nbsp;Kattints ide a csatolt kép megnyitásához!</a></div>\n";
			$pic2 = $pic1;
			$pic3 = $pic1;
			$pic4 = $pic1;
			$pic5 = $pic1;
			$pic6 = $pic1;
			$pic7 = $pic1;
		} else {
			$pic1 = "<img class=\"bb-image\" width=\"\\1\" height=\"\\2\" src=\"\\3\" alt=\"\\3\"/>";
			$pic2 = "<img class=\"bb-image\" src=\"\\1\" alt=\"\\1\"/>";
			$pic3 = "<img class=\"bb-image\" src=\"\\1\" alt=\"\\1\"/>";
			$pic4 = "<img class=\"bb-image\" width=\"550\" src=\"\\1\" alt=\"\\1\"/><br/><span class=\"small\">Ez egy átméretezett kép, <a href=\"\\1\" target=\"_blank\">kattints ide</a> az eredeti méretben való megjelenítéséhez.</span>";
			$pic5 = "<img class=\"bb-image\" width=\"550\" src=\"\\1\" alt=\"\\1\"/><br/><span class=\"small\">Ez egy átméretezett kép, <a href=\"\\1\" target=\"_blank\">kattints ide</a> az eredeti méretben való megjelenítéséhez.</span>";
			$pic6 = "<a class=\"pic\" href=\"\\1\" title=\"\\1\"><img class=\"bb-image\" src=\"\\1\" alt=\"\\1\"/></a>";
			$pic7 = "<a class=\"pic\" href=\"\\1\" title=\"\\1\"><img class=\"bb-image\" width=\"550\" src=\"\\2\" alt=\"\\1\"/></a><br/><span class=\"small\">Ez egy átméretezett kép, <a href=\"\\2\" target=\"_blank\">kattints ide</a> az eredeti méretben való megjelenítéséhez.</span>";
		}
		$browser = self::whatbrowser();
		
		if($browser['browser'] == 'MSIE') {
			$flash = "<object type=\"application/x-shockwave-flash\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\"\\1\" height=\"\\2\"><param name=\"movie\" value=\"\\3\"/><param name=\"quality\" value=\"high\"/></object>";
			$media = "<object type=\"application/x-oleobject\" classid=\"clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6\" width=\"\\1\" height=\"\\2\"><param name=\"url\" value=\"\\3\"/><param name=\"autostart\" value=\"0\"/></object>";
		} else {
			$flash = "<object type=\"application/x-shockwave-flash\" data=\"\\3\" width=\"\\1\" height=\"\\2\"><param name=\"movie\" value=\"\\3\"/><param name=\"quality\" value=\"high\"/></object>";
			$media = "<object type=\"application/asx\" data=\"\\3\" width=\"\\1\" height=\"\\2\"><param name=\"url\" value=\"\\3\"/><param name=\"autostart\" value=\"0\"/></object>";
		}
		
		$preg = array(
			'/(?<!\\\\)\[admin](.*?)\[\/admin]/si'									=> "<div class=\"forum_admin\">\\1</div>",

			// Alap formazasok
			'/(?<!\\\\)\[color(?::\w+)?=(.*?)\](.*?)\[\/color(?::\w+)?\]/si'									=> "<span style=\"color: \\1;\">\\2</span>",
			'/(?<!\\\\)\[size(?::\w+)?=(.*?)\](.*?)\[\/size(?::\w+)?\]/si'										=> "<span style=\"font-size: \\1;\">\\2</span>",
			'/(?<!\\\\)\[font(?::\w+)?=(.*?)\](.*?)\[\/font(?::\w+)?\]/si'										=> "<span style=\"font-family: \\1;\">\\2</span>",
			'/(?<!\\\\)\[b(?::\w+)?\](.*?)\[\/b(?::\w+)?\]/si'													=> "<span style=\"font-weight: bold;\">\\1</span>",
			'/(?<!\\\\)\[i(?::\w+)?\](.*?)\[\/i(?::\w+)?\]/si'													=> "<span style=\"font-style: italic;\">\\1</span>",
			'/(?<!\\\\)\[u(?::\w+)?\](.*?)\[\/u(?::\w+)?\]/si'													=> "<span style=\"text-decoration: underline;\">\\1</span>",
			'/(?<!\\\\)\[o(?::\w+)?\](.*?)\[\/o(?::\w+)?\]/si'													=> "<span style=\"text-decoration: overline;\">\\1</span>",
			'/(?<!\\\\)\[x(?::\w+)?\](.*?)\[\/x(?::\w+)?\]/si'													=> "<span style=\"text-decoration: line-through;\">\\1</span>",
			'/(?<!\\\\)\[f(?::\w+)?\](.*?)\[\/f(?::\w+)?\]/si'													=> "<span style=\"text-decoration: blink;\">\\1</span>",
			'/(?<!\\\\)\[align(?::\w+)?=(.*?)\](.*?)\[\/align(?::\w+)?\]/si'									=> "<div style=\"text-align: \\1;\">\\2</div>",
			'/(?<!\\\\)\[left(?::\w+)?\](.*?)\[\/left(?::\w+)?\]/si'											=> "<div style=\"text-align: left;\">\\1</div>",
			'/(?<!\\\\)\[center(?::\w+)?\](.*?)\[\/center(?::\w+)?\]/si'										=> "<div style=\"text-align: center;\">\\1</div>",
			'/(?<!\\\\)\[right(?::\w+)?\](.*?)\[\/right(?::\w+)?\]/si'											=> "<div style=\"text-align: right;\">\\1</div>",
			'/(?<!\\\\)\[justify(?::\w+)?\](.*?)\[\/justify(?::\w+)?\]/si'										=> "<div style=\"text-align: justify;\">\\1</div>",
			'/(?<!\\\\)\[tab(?::\w+)?\](.*?)\[\/tab(?::\w+)?\]/si'												=> "<div style=\"padding-left: 30px;\">\\1</div>",
			'/(?<!\\\\)\[list(?::\w+)?\](.*?)\[\/list(?::\w+)?\]/si'											=> "<ul><li>\\1</li></ul>",
			'/\[\-\]/'																							=> "</li><li>",
			'/\n/'																								=> "<br/>",
			'/\r\n/'																							=> "<br/>",
	
			// \[b], \[color], \[url], ...
			'/\\\\(\[\/?\w+(?::\w+)*\])/'																		=> "\\1",
	
			// [url][img][/url]
			'/(?<!\\\\)\[url\]\[img(?::\w+)?\](.*?)\[\/img(?::\w+)?\]\[\/url\]/si'								=> $pic6,
			'/(?<!\\\\)\[url\]\[img(?::\w+)?=(.*?)(?::\w+)?\]\[\/url\]/si'										=> $pic6,
	
			// [url][imgw][/url]
			'/(?<!\\\\)\[url(?::\w+)?=(.*?)?\]\[imgw(?::\w+)?\](.*?)\[\/imgw(?::\w+)?\]\[\/url(?::\w+)?\]/si'	=> $pic7,
			'/(?<!\\\\)\[url(?::\w+)?=(.*?)?\]\[imgw(?::\w+)?=(.*?)(?::\w+)?\]\[\/url(?::\w+)?\]/si'			=> $pic7,
	
			// [url]
			'/(?<!\\\\)\[url(?::\w+)?\]www\.(.*?)\[\/url(?::\w+)?\]/si'											=> "<a href=\"http://www.\\1\" target=\"_blank\">\\1</a>",
			'/(?<!\\\\)\[url(?::\w+)?\](.*?)\[\/url(?::\w+)?\]/si'												=> "<a href=\"\\1\" target=\"_blank\">\\1</a>",
			'/(?<!\\\\)\[url(?::\w+)?=(.*?)?\](.*?)\[\/url(?::\w+)?\]/si'										=> "<a href=\"\\1\" target=\"_blank\">\\2</a>",
	
			// [img]
			'/(?<!\\\\)\[imgx(?::\w+)?=(.*?)x(.*?)\](.*?)\[\/imgx(?::\w+)?\]/si'								=> $pic1,
			'/(?<!\\\\)\[img(?::\w+)?\](.*?)\[\/img(?::\w+)?\]/si'												=> $pic2,
			'/(?<!\\\\)\[img(?::\w+)?=(.*?)(?::\w+)?\]/si'														=> $pic3,
			'/(?<!\\\\)\[imgw(?::\w+)?\](.*?)\[\/imgw(?::\w+)?\]/si'											=> $pic4,
			'/(?<!\\\\)\[imgw(?::\w+)?=(.*?)(?::\w+)?\]/si'														=> $pic5,

			// [google]
			'/(?<!\\\\)\[google(?::\w+)?\](.*?)\[\/google(?::\w+)?\]/si'										=> "<a href=\"http://www.google.com/search?hl=hu&amp;q=\\1\" title=\"Google keresés: \\1\" target=\"_blank\">\\1</a><sup><span style=\"font-size: 7pt;\"><span style=\"color: #1645AE;\">G</span><span style=\"color: #D62408;\">o</span><span style=\"color: #EFBA00;\">o</span><span style=\"color: #1645AE;\">g</span><span style=\"color: #007D08;\">l</span><span style=\"color: #D62408;\">e</span></span></sup>",
			'/(?<!\\\\)\[google(?::\w+)?=(.*?)\](.*?)\[\/google(?::\w+)?\]/si'									=> "<a href=\"http://www.google.com/search?hl=hu&amp;q=\\2\" title=\"Google keresés: \\2\" target=\"_blank\">\\1</a><sup><span style=\"font-size: 7pt;\"><span style=\"color: #1645AE;\">G</span><span style=\"color: #D62408;\">o</span><span style=\"color: #EFBA00;\">o</span><span style=\"color: #1645AE;\">g</span><span style=\"color: #007D08;\">l</span><span style=\"color: #D62408;\">e</span></span></sup>",
	
			// [email]
			'/(?<!\\\\)\[email(?::\w+)?\](.*?)\[\/email(?::\w+)?\]/si'											=> "<a href=\"mailto:\\1\">\\1</a>",
			'/(?<!\\\\)\[email(?::\w+)?=(.*?)\](.*?)\[\/email(?::\w+)?\]/si'									=> "<a href=\"mailto:\\1\">\\2</a>",

			// [smilies]
			'/(?<!\\\\)\[smyle(?::\w+)?=(.*?)(?::\w+)?\]/si'													=> "<img border=\"0\" src=\"kinezet/smilies/\\1\" alt=\"\" class=\"smiley\"/>",

			// [quote]
			'/(?<!\\\\)\[quote(?::\w+)?\](.*?)\[\/quote(?::\w+)?\]/si'											=> "<div class=\"bb-quote\"><span class=\"bb-quote-title\">Idézet:</span><div class=\"layer\">\\1</div></div>",
			'/(?<!\\\\)\[quote(?::\w+)?=(?:&quot;|"|\')?(.*?)["\']?(?:&quot;|"|\')?\](.*?)\[\/quote\]/si'		=> "<div class=\"bb-quote\"><span class=\"bb-quote-title\">\\1 írta:</span><div class=\"layer\">\\2</div></div>",

			// [list]
			'/\[\*\]/'																							=> "&bull;&nbsp;",

			// Flash
			'/(?<!\\\\)\[swf(?::\w+)?=(.*?)x(.*?)\](.*?)\[\/swf(?::\w+)?\]/si'									=> $flash,

			// Media
			'/(?<!\\\\)\[wmp(?::\w+)?=(.*?)x(.*?)\](.*?)\[\/wmp(?::\w+)?\]/si'									=> $media,

			// Redirecting URLs
			"/href=\\\"((http|ftp|https|ftps|irc):\/\/[^()<>\s]+)\\\"/i"										=> "href=\"\\1\""
		);

		$message = str_replace(self::$smilies_code, self::$smilies_img, htmlspecialchars($message));
		$message = preg_replace(array_keys($preg), array_values($preg), $message);
		return $message;
	}

	function getImg() {
		return self::$smilies_img;
	}

	function getCode() {
		return self::$smilies_code;
	}
}

?>
